### ISSUE TITLE
[Bug] typo in README (`Raedme Generator`)

### ISSUE THREAD

**Issue by CarlosSanabriaM** [lobehub/lobe-readme-wizard#18]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Other

### 🐛 问题描述 | Bug Description

There is a typo in the README:
<img width="259" alt="typo" src="https://github.com/lobehub/lobe-readme-wizard/assets/35775214/89d93b9e-d83d-4845-909d-25e5bd5acf31">

### 🚦 期望结果 | Expected Behavior

`Readme Generator` should be written instead.

**Comment by canisminor1990** [comment]
thanks for checking 👀
